spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v13?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
  data:
    solr:
      host: http://192.168.17.128:8088/solr
dubbo:
  application:
    name: product-service
  registry:
    protocol: zookeeper
    address: 192.168.17.128:2181
  protocol:
    port: 28811




