dubbo:
  application:
    name: center-web
  registry:
    protocol: zookeeper
    address: 192.168.17.128:2181
spring:
  thymeleaf:
    cache: false
server:
  port: 9090


fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.17.128:22122

image:
  server: http://192.168.17.128/
